# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0002_auto_20191107_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='profiles',
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
